name: Manual Selenium Cucumber Test

on:
  workflow_dispatch:
    inputs:
      FEATURE:
        description: 'Feature to test'
        required: true
        type: string
      TITLE:
        description: 'The title from Slack'
        required: false
        type: string
      PD_COMMIT:
        description: 'PD Commit SHA'
        required: false
        default: 'N/A'
        type: string
      BIZ_COMMIT:
        description: 'Biz Commit SHA'
        required: false
        default: 'N/A'
        type: string
      slack_thread_url:
        description: 'The URL for the Slack thread'
        required: true
        type: string

  # Keep automatic trigger for pushes if you want (optional)
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Cucumber Tests
        # We use the ${{ github.event.inputs.tags }} to pass the UI input to Maven
        run: |
          mvn test -Dcucumber.filter.tags="${{ github.event.inputs.tags || '@Login' }}"

      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: target/cucumber-reports/

      - name: Notify Slack
        if: always()
        uses: ./.github/actions/slack-notify
        with:
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }} # Use the token here
          slack-thread-url: ${{ github.event.inputs.slack_thread_url }}
          test-result: ${{ job.status }}
          feature-name: ${{ github.event.inputs.FEATURE }}
          passed: '20'
          failed: '0'
